1.#include<iostream>
2.#include<string>
3.#include<vector>
4.#include<list>
5.#include<map>
6.#include<queue>
7.#include<deque>
8.#include<set>
9.#include<bitset>
10.#include<stack>
11.#include<typeinfo>
12.#include<memory>
13.#include<exception>
14.#include<stdexcept>
15.#include<iomanhip>
16.#include<iterator>
17.#include<algorithm>
18.#include<locale>
19.#include<functional>
20.#include<sstream>
21.#include<cstdlib>
22.#include<cmath>
23.#include<ctime>
24.#include<cctype>
25.#include<cstring>
26.#include<cstdio>
27.#include<climits>
28.#include<cassert>
29.#include<cfloat>
30.#include<fstream>
31.#include<utility>
